<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="SeliseBlocks.Genesis.OS" />
        <PackageReference Include="MongoDB.Driver" />
        <PackageReference Include="Azure.Storage.Blobs" />
        <PackageReference Include="AWSSDK.S3" />
        <PackageReference Include="SSH.NET" />
        <PackageReference Include="SeliseBlocks.StorageDriver.OS" />
        <PackageReference Include="SeliseBlocks.MailDriver.OS" />
    </ItemGroup>

</Project>
