<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DeviceDetector.NET" />
    <PackageReference Include="Handlebars.Net" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cloud.DomainService\Cloud.DomainService.csproj" />
    <ProjectReference Include="..\Iam.DomainService\Iam.DomainService.csproj" />
    <ProjectReference Include="..\Mfa.DomainService\Mfa.DomainService.csproj" />
  </ItemGroup>

</Project>
