export const API_BASES = {
  COMMUNICATION: "/api",
  CLOUD_CONFIGURATION: "/api",
  UDS: import.meta.env.BLOCKS_UDS_API_BASE_URL + "/api",
  UILM: "/api",
  UTILITIES: "/api",
  CLOUD_BUILD: "/api",
  IDP: import.meta.env.BLOCKS_IDP_API_BASE_URL + "/api",
  IDENTIFIER: "/api",
  LMT: "/api",
  MFA: "/api",
  ALERT: "/api",
  AI: import.meta.env.BLOCKS_AGENT_API_BASE_URL + "/api",
  STUDIO: "/api",
  WORKFLOW: "/api",
  EUROLM: import.meta.env.BLOCKS_EUROLM_API_BASE_URL + "/api",
  UTILITY: import.meta.env.BLOCKS_UTILITY_API_BASE_URL + "/api",
} as const;
