<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
	  <PackageReference Include="Azure.ResourceManager.ServiceBus" />
	  <PackageReference Include="FluentValidation" />
	
	  <PackageReference Include="SeliseBlocks.StorageDriver.OS" />
	  <PackageReference Include="SixLabors.Fonts" />
    <PackageReference Include="SeliseBlocks.Genesis.OS" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mail.DomainService\Mail.DomainService.csproj" />
  </ItemGroup>

  

</Project>
