<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
	  <PackageReference Include="Azure.ResourceManager.ServiceBus" />
	  <PackageReference Include="FluentValidation" />
	  <PackageReference Include="SeliseBlocks.MailDriver.OS" />
	  <PackageReference Include="SeliseBlocks.StorageDriver.OS" />
	  <PackageReference Include="SixLabors.Fonts" />
    <PackageReference Include="SeliseBlocks.Genesis.OS" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Captcha.DomainService\Captcha.DomainService.csproj" />
    <ProjectReference Include="..\Iam.DomainService\Iam.DomainService.csproj" />
  </ItemGroup>

  

</Project>
