import { Proxy, ProxyExecutionLog, ProxyVersionHistory } from "../types";

export const PROXY_MOCK_DATA: Proxy[] = [
  {
    id: "p1",
    name: "Stripe Payments",
    slug: "stripe-payments",
    upstreamUrl: "https://api.stripe.com/v1/charges",
    upstreamMasked: "https://api.stripe.com/v1/.../charges",
    methods: ["GET", "POST"],
    enabled: true,
    headers: [{ key: "Authorization", value: "${SECRET.STRIPE_API_KEY}", isSecretRef: true }],
    query: [{ key: "expand[]", value: "payment_intent" }],
    bodyMerge: [
      { key: "account", value: "acct_platform", isSecretRef: false },
      { key: "idempotency_key", value: "${SECRET.STRIPE_IDEMPOTENCY}", isSecretRef: true },
    ],
    methodConfigs: [
      {
        method: "POST",
        upstream: "https://api.stripe.com/v2/charges",
        headers: [{ key: "X-Trace", value: "on", isSecretRef: false }],
        query: null,
      },
    ],
    calls24h: 1248,
    createdAt: "2026-04-12T09:15:00.000Z",
    updatedAt: "2026-09-01T11:30:00.000Z",
  },
  {
    id: "p2",
    name: "SendGrid Mail",
    slug: "sendgrid-mail",
    upstreamUrl: "https://api.sendgrid.com/v3/mail/send",
    upstreamMasked: "https://api.sendgrid.com/v3/.../send",
    methods: ["POST"],
    enabled: true,
    headers: [{ key: "Authorization", value: "${SECRET.SENDGRID_API_KEY}", isSecretRef: true }],
    query: [],
    bodyMerge: [],
    methodConfigs: [],
    calls24h: 382,
    createdAt: "2026-05-02T14:00:00.000Z",
    updatedAt: "2026-08-27T08:45:00.000Z",
  },
  {
    id: "p3",
    name: "Weather Lookup",
    slug: "weather-lookup",
    upstreamUrl: "https://api.weatherapi.com/v1/current.json",
    upstreamMasked: "https://api.weatherapi.com/v1/.../current.json",
    methods: ["GET"],
    enabled: false,
    headers: [],
    query: [{ key: "key", value: "${SECRET.WEATHER_API_KEY}", isSecretRef: true }],
    bodyMerge: [],
    methodConfigs: [],
    calls24h: 74,
    createdAt: "2026-06-18T10:20:00.000Z",
    updatedAt: "2026-08-30T16:10:00.000Z",
  },
];

export const PROXY_MOCK_EXECUTION_LOGS: ProxyExecutionLog[] = [
  {
    id: "l1",
    proxyId: "p1",
    timeUtc: "2026-09-07T05:12:11.000Z",
    method: "POST",
    path: "/api/proxy/gateway/stripe-payments/charges",
    status: 200,
    statusText: "OK",
    latencyMs: 184,
    upstreamHost: "api.stripe.com",
    upstreamUrl: "https://api.stripe.com/v1/charges",
    injectedHeaderKeys: ["Authorization"],
    injectedQueryKeys: ["expand[]"],
    responseBody: '{\n  "id": "ch_mock_123",\n  "status": "succeeded"\n}',
    responseContentType: "application/json",
  },
  {
    id: "l2",
    proxyId: "p1",
    timeUtc: "2026-09-07T04:58:41.000Z",
    method: "GET",
    path: "/api/proxy/gateway/stripe-payments/charges/ch_404",
    status: 404,
    statusText: "Not Found",
    latencyMs: 96,
    upstreamHost: "api.stripe.com",
    upstreamUrl: "https://api.stripe.com/v1/charges/ch_404",
    injectedHeaderKeys: ["Authorization"],
    injectedQueryKeys: [],
    responseBody: '{\n  "error": "Charge was not found"\n}',
    responseContentType: "application/json",
  },
  {
    id: "l3",
    proxyId: "p1",
    timeUtc: "2026-09-07T04:43:20.000Z",
    method: "POST",
    path: "/api/proxy/gateway/stripe-payments/charges",
    status: 502,
    statusText: "Bad Gateway",
    latencyMs: 1200,
    upstreamHost: "api.stripe.com",
    upstreamUrl: "https://api.stripe.com/v1/charges",
    injectedHeaderKeys: ["Authorization"],
    injectedQueryKeys: ["expand[]"],
    responseBody: '{\n  "error": "Upstream timeout"\n}',
    responseContentType: "application/json",
  },
  {
    id: "l4",
    proxyId: "p2",
    timeUtc: "2026-09-07T04:20:00.000Z",
    method: "POST",
    path: "/api/proxy/gateway/sendgrid-mail/send",
    status: 202,
    statusText: "Accepted",
    latencyMs: 241,
    upstreamHost: "api.sendgrid.com",
    upstreamUrl: "https://api.sendgrid.com/v3/mail/send",
    injectedHeaderKeys: ["Authorization"],
    injectedQueryKeys: [],
    responseBody: "{\n  \"queued\": true\n}",
    responseContentType: "application/json",
  },
  {
    id: "l5",
    proxyId: "p3",
    timeUtc: "2026-09-07T03:50:00.000Z",
    method: "GET",
    path: "/api/proxy/gateway/weather-lookup/current.json",
    status: 401,
    statusText: "Unauthorized",
    latencyMs: 110,
    upstreamHost: "api.weatherapi.com",
    upstreamUrl: "https://api.weatherapi.com/v1/current.json",
    injectedHeaderKeys: [],
    injectedQueryKeys: ["key"],
    responseBody: "{\n  \"error\": \"Missing API key\"\n}",
    responseContentType: "application/json",
  },
];

export const PROXY_MOCK_VERSION_HISTORY: ProxyVersionHistory[] = [
  {
    id: "v5",
    proxyId: "p1",
    versionLabel: "v5",
    versionNumber: 5,
    kind: "edit",
    summary: "body field account added",
    actor: "755991d9-6c90-4f12-b710-8cb896075a35",
    actorName: "Avery Stone",
    whenUtc: "2026-09-03T08:00:00.000Z",
    changes: [
      {
        field: "body:account",
        label: "body field account",
        before: null,
        after: "acct_platform",
      },
    ],
  },
  {
    id: "v4",
    proxyId: "p1",
    versionLabel: "v4",
    versionNumber: 4,
    kind: "edit",
    summary: "POST header X-Trace overridden.",
    actor: "755991d9-6c90-4f12-b710-8cb896075a35",
    actorName: "Avery Stone",
    whenUtc: "2026-09-02T09:00:00.000Z",
    changes: [
      {
        field: "method:POST:header:X-Trace",
        label: "POST header X-Trace",
        before: null,
        after: "on",
      },
    ],
  },
  {
    id: "v3",
    proxyId: "p1",
    versionLabel: "v3",
    versionNumber: 3,
    kind: "edit",
    summary: "Added payment intent expansion query.",
    actor: "755991d9-6c90-4f12-b710-8cb896075a35",
    actorName: "Avery Stone",
    whenUtc: "2026-09-01T11:30:00.000Z",
    changes: [
      {
        field: "query:expand[]",
        label: "query expand[]",
        before: null,
        after: "payment_intent",
      },
    ],
  },
  {
    id: "v2",
    proxyId: "p1",
    versionLabel: "v2",
    versionNumber: 2,
    kind: "toggle",
    summary: "Enabled proxy traffic.",
    actor: "3f2a1b6c-8d4e-4a91-b0c2-1e5f7a9d3c40",
    actorName: "Mina Patel",
    whenUtc: "2026-08-22T10:00:00.000Z",
    changes: [
      { field: "enabled", label: "status", before: "disabled", after: "enabled" },
    ],
  },
  {
    id: "v1",
    proxyId: "p1",
    versionLabel: "v1",
    versionNumber: 1,
    kind: "create",
    summary: "Created proxy configuration.",
    actor: "755991d9-6c90-4f12-b710-8cb896075a35",
    actorName: "Avery Stone",
    whenUtc: "2026-04-12T09:15:00.000Z",
    changes: [],
  },
];
