<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="XUnitTest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cronos" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.MemoryStorage" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="SeliseBlocks.Genesis.OS" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

</Project>
