import { API_BASES } from "@/constants/endpoint.constant";


const WORKFLOW_SUBPATH = "/Workflow";

export const WORKFLOW_ENDPOINTS = {
  GET_ALL: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/GetAll`,
  GET: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/Get`,
  CREATE: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/Create`,
  DUPLICATE: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/Duplicate`,
  UPDATE: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/Update`,
  DELETE: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/Delete`,
  GET_EXECUTIONS: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/GetExecutions`,
  GET_EXECUTION: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/GetExecution`,
  CREATE_VERSION: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/createVersion`,
  GET_VERSIONS: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/getVersions`,
  PUBLISH: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/publish`,
  UNPUBLISH: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/unpublish`,
  RESTORE: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/restore`,
  GET_WORKFLOW_BY_VERSION: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/getWorkflowByVersion`,
  UPDATE_VERSION: `${API_BASES.WORKFLOW}${WORKFLOW_SUBPATH}/updateVersion`,
} as const;
