<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="SeliseBlocks.ConfigurationDriver" />
    <PackageReference Include="SeliseBlocks.Genesis.OS" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Workflow.DomainService\Workflow.DomainService.csproj" />
    <ProjectReference Include="..\Mail.DomainService\Mail.DomainService.csproj" />
  </ItemGroup>

</Project>
