<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="FluentValidation" />
	  <PackageReference Include="Otp.NET"  />
	  <PackageReference Include="QRCoder" />
	  <PackageReference Include="SeliseBlocks.MailDriver" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Iam.DomainService\Iam.DomainService.csproj" />
  </ItemGroup>

</Project>
