import { API_BASES } from "@/constants/endpoint.constant";

const FUNCTIONS_SUBPATH = "/Functions";
const FUNCTION_INVOKE_SUBPATH = "/fn";

export const FUNCTIONS_ENDPOINTS = {
  CREATE: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/Create`,
  UPDATE: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/Update`,
  SAVE: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/Save`,
  DELETE: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/Delete`,
  GET_ALL: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/GetAll`,
  GET: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/Get`,
  GET_LIMITS: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/GetLimits`,
  TEST: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/Test`,
  DEPLOY: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/Deploy`,
  ROLLBACK: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/Rollback`,
  GET_VERSIONS: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/GetVersions`,
  GET_VERSION_SOURCE: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/GetVersionSource`,
  GET_BUILD: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/GetBuild`,
  GET_RUNS: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/GetRuns`,
  GET_RUN: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/GetRun`,
  GET_RUN_LOGS: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/GetRunLogs`,
  REPLAY_RUN: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/ReplayRun`,
  CANCEL_RUN: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/CancelRun`,
  GET_AUDIT_LOG: `${API_BASES.WORKFLOW}${FUNCTIONS_SUBPATH}/GetAuditLog`,
} as const;

/** Public invocation endpoint (`FunctionInvokeController`) — shown to the tenant as their function's URL, never called by this client itself. */
export const FUNCTION_INVOKE_ENDPOINT_BASE = `${API_BASES.WORKFLOW}${FUNCTION_INVOKE_SUBPATH}`;
